/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author ar316b
 */
public class Banco extends javax.swing.JFrame {

    /**
     * Creates new form Banco
     */
    public Banco() {
        initComponents();
        this.setTitle("banco de prubeas");
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagen/banco.png"));
        lblLogo.setIcon(new ImageIcon(img.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH)));
        this.setIconImage(img);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarCliente = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cbolistaClientes = new javax.swing.JComboBox<>();
        cbolistaTipoCuenta = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbolistaCuenta = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtMontoMovimiento = new javax.swing.JTextField();
        btnRealizarMovimiento = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovimientos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblidCliente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTipoCuenta = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblBalanceCliente = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboCuentaCliente = new javax.swing.JComboBox<>();
        btnAgregarTipoCuenta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMontoInicial = new javax.swing.JTextField();
        btnAgregarCuenta = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cboTipoCuenta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/banco.png"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Telefono");

        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Identificacion:");

        txtIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificacionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        btnAgregarCliente.setBackground(new java.awt.Color(204, 255, 204));
        btnAgregarCliente.setText("Agregar Cliente");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });


        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Movimientos"));


        cbolistaTipoCuenta.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        cbolistaTipoCuenta.setText("Tipo de cuenta");


        jLabel8.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Movimiento:");

        cbolistaCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposito", "Retiro" }));

        jLabel9.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Monto:");

        txtMontoMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoMovimientoActionPerformed(evt);
            }
        });

        btnRealizarMovimiento.setBackground(new java.awt.Color(204, 255, 204));
        btnRealizarMovimiento.setText("Realizar movimiento");
        btnRealizarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarMovimientoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel11.setText("Cliente:");


        tblMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMovimientos);


        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Cliente"));

        jLabel10.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Nombre:");

        lblNombreCliente.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel12.setText("Identificacion");

        lblidCliente.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel14.setText("Tipo Cuenta");

        lblTipoCuenta.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel16.setText("Balance");

        lblBalanceCliente.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N


        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Cliente:");

        cboCuentaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCuentaClienteActionPerformed(evt);
            }
        });

        btnAgregarTipoCuenta.setText("+");
        btnAgregarTipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTipoCuentaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Monto inicial");

        txtMontoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoInicialActionPerformed(evt);
            }
        });

        btnAgregarCuenta.setBackground(new java.awt.Color(204, 255, 204));
        btnAgregarCuenta.setText("Agregar Cuenta");
        btnAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        jLabel18.setText("Tipo de cuenta");



        pack();
    }// </editor-fold>                        

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txtIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void txtMontoInicialActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void txtMontoMovimientoActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void btnRealizarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void btnAgregarTipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void cboCuentaClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarCuenta;
    private javax.swing.JButton btnAgregarTipoCuenta;
    private javax.swing.JButton btnRealizarMovimiento;
    private javax.swing.JComboBox<String> cboCuentaCliente;
    private javax.swing.JComboBox<String> cboTipoCuenta;
    private javax.swing.JComboBox<String> cbolistaClientes;
    private javax.swing.JComboBox<String> cbolistaCuenta;
    private javax.swing.JLabel cbolistaTipoCuenta;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBalanceCliente;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblTipoCuenta;
    private javax.swing.JLabel lblidCliente;
    private javax.swing.JTable tblMovimientos;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtMontoInicial;
    private javax.swing.JTextField txtMontoMovimiento;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration                   
}
